url: fix builds with `CURL_DISABLE_HTTP`
Fixes:
```
./lib/url.c:456:35: error: no member named 'formp' in 'struct UrlState'
  456 |   Curl_mime_cleanpart(data->state.formp);
      |                       ~~~~~~~~~~~ ^
```

Regression from 7365af09f28b873ce4bc7634c44e401593f0dd17 #11682

Closes #12343