http_digest: Fixed compilation errors from commit 238b47ee3b
error: invalid operands to binary
warning: pointer targets in assignment differ in signedness